"""adding activity streams

Revision ID: b051e46f81c5
Revises: 1410c6804472
Create Date: 2026-05-05 23:11:20.314045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b051e46f81c5'
down_revision = '1410c6804472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_stream',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('heartrate', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('pace', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_stream', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_stream_activity_id'), ['activity_id'], unique=False)

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refresh_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('expires_at', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('expires_at')
        batch_op.drop_column('refresh_token')

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('activity_stream', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_stream_activity_id'))

    op.drop_table('activity_stream')
    # ### end Alembic commands ###
